// Generated by tools/import-scale-assets.mjs from the authoritative manifest. Do not edit mappings.
export const scaleAssets = [
  {
    "assetId": "accid-0-major",
    "keySignatureId": "0",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-0-major.svg"
  },
  {
    "assetId": "accid-0-minor-harmonic",
    "keySignatureId": "0",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-0-minor-harmonic.svg"
  },
  {
    "assetId": "accid-0-minor-melodic-asc",
    "keySignatureId": "0",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-0-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-0-minor-melodic-desc",
    "keySignatureId": "0",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-0-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-0-minor-natural",
    "keySignatureId": "0",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-0-minor-natural.svg"
  },
  {
    "assetId": "accid-f1-major",
    "keySignatureId": "1f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f1-major.svg"
  },
  {
    "assetId": "accid-f1-minor-harmonic",
    "keySignatureId": "1f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f1-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f1-minor-melodic-asc",
    "keySignatureId": "1f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f1-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f1-minor-melodic-desc",
    "keySignatureId": "1f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f1-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f1-minor-natural",
    "keySignatureId": "1f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f1-minor-natural.svg"
  },
  {
    "assetId": "accid-f2-major",
    "keySignatureId": "2f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f2-major.svg"
  },
  {
    "assetId": "accid-f2-minor-harmonic",
    "keySignatureId": "2f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f2-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f2-minor-melodic-asc",
    "keySignatureId": "2f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f2-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f2-minor-melodic-desc",
    "keySignatureId": "2f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f2-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f2-minor-natural",
    "keySignatureId": "2f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f2-minor-natural.svg"
  },
  {
    "assetId": "accid-f3-major",
    "keySignatureId": "3f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f3-major.svg"
  },
  {
    "assetId": "accid-f3-minor-harmonic",
    "keySignatureId": "3f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f3-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f3-minor-melodic-asc",
    "keySignatureId": "3f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f3-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f3-minor-melodic-desc",
    "keySignatureId": "3f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f3-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f3-minor-natural",
    "keySignatureId": "3f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f3-minor-natural.svg"
  },
  {
    "assetId": "accid-f4-major",
    "keySignatureId": "4f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f4-major.svg"
  },
  {
    "assetId": "accid-f4-minor-harmonic",
    "keySignatureId": "4f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f4-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f4-minor-melodic-asc",
    "keySignatureId": "4f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f4-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f4-minor-melodic-desc",
    "keySignatureId": "4f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f4-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f4-minor-natural",
    "keySignatureId": "4f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f4-minor-natural.svg"
  },
  {
    "assetId": "accid-f5-major",
    "keySignatureId": "5f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f5-major.svg"
  },
  {
    "assetId": "accid-f5-minor-harmonic",
    "keySignatureId": "5f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f5-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f5-minor-melodic-asc",
    "keySignatureId": "5f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f5-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f5-minor-melodic-desc",
    "keySignatureId": "5f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f5-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f5-minor-natural",
    "keySignatureId": "5f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f5-minor-natural.svg"
  },
  {
    "assetId": "accid-f6-major",
    "keySignatureId": "6f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f6-major.svg"
  },
  {
    "assetId": "accid-f6-minor-harmonic",
    "keySignatureId": "6f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f6-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f6-minor-melodic-asc",
    "keySignatureId": "6f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f6-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f6-minor-melodic-desc",
    "keySignatureId": "6f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f6-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f6-minor-natural",
    "keySignatureId": "6f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f6-minor-natural.svg"
  },
  {
    "assetId": "accid-f7-major",
    "keySignatureId": "7f",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f7-major.svg"
  },
  {
    "assetId": "accid-f7-minor-harmonic",
    "keySignatureId": "7f",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f7-minor-harmonic.svg"
  },
  {
    "assetId": "accid-f7-minor-melodic-asc",
    "keySignatureId": "7f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f7-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-f7-minor-melodic-desc",
    "keySignatureId": "7f",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-f7-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-f7-minor-natural",
    "keySignatureId": "7f",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-f7-minor-natural.svg"
  },
  {
    "assetId": "accid-s1-major",
    "keySignatureId": "1s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s1-major.svg"
  },
  {
    "assetId": "accid-s1-minor-harmonic",
    "keySignatureId": "1s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s1-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s1-minor-melodic-asc",
    "keySignatureId": "1s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s1-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s1-minor-melodic-desc",
    "keySignatureId": "1s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s1-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s1-minor-natural",
    "keySignatureId": "1s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s1-minor-natural.svg"
  },
  {
    "assetId": "accid-s2-major",
    "keySignatureId": "2s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s2-major.svg"
  },
  {
    "assetId": "accid-s2-minor-harmonic",
    "keySignatureId": "2s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s2-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s2-minor-melodic-asc",
    "keySignatureId": "2s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s2-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s2-minor-melodic-desc",
    "keySignatureId": "2s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s2-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s2-minor-natural",
    "keySignatureId": "2s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s2-minor-natural.svg"
  },
  {
    "assetId": "accid-s3-major",
    "keySignatureId": "3s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s3-major.svg"
  },
  {
    "assetId": "accid-s3-minor-harmonic",
    "keySignatureId": "3s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s3-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s3-minor-melodic-asc",
    "keySignatureId": "3s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s3-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s3-minor-melodic-desc",
    "keySignatureId": "3s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s3-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s3-minor-natural",
    "keySignatureId": "3s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s3-minor-natural.svg"
  },
  {
    "assetId": "accid-s4-major",
    "keySignatureId": "4s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s4-major.svg"
  },
  {
    "assetId": "accid-s4-minor-harmonic",
    "keySignatureId": "4s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s4-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s4-minor-melodic-asc",
    "keySignatureId": "4s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s4-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s4-minor-melodic-desc",
    "keySignatureId": "4s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s4-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s4-minor-natural",
    "keySignatureId": "4s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s4-minor-natural.svg"
  },
  {
    "assetId": "accid-s5-major",
    "keySignatureId": "5s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s5-major.svg"
  },
  {
    "assetId": "accid-s5-minor-harmonic",
    "keySignatureId": "5s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s5-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s5-minor-melodic-asc",
    "keySignatureId": "5s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s5-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s5-minor-melodic-desc",
    "keySignatureId": "5s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s5-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s5-minor-natural",
    "keySignatureId": "5s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s5-minor-natural.svg"
  },
  {
    "assetId": "accid-s6-major",
    "keySignatureId": "6s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s6-major.svg"
  },
  {
    "assetId": "accid-s6-minor-harmonic",
    "keySignatureId": "6s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s6-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s6-minor-melodic-asc",
    "keySignatureId": "6s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s6-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s6-minor-melodic-desc",
    "keySignatureId": "6s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s6-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s6-minor-natural",
    "keySignatureId": "6s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s6-minor-natural.svg"
  },
  {
    "assetId": "accid-s7-major",
    "keySignatureId": "7s",
    "scaleType": "major",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s7-major.svg"
  },
  {
    "assetId": "accid-s7-minor-harmonic",
    "keySignatureId": "7s",
    "scaleType": "harmonic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s7-minor-harmonic.svg"
  },
  {
    "assetId": "accid-s7-minor-melodic-asc",
    "keySignatureId": "7s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s7-minor-melodic-asc.svg"
  },
  {
    "assetId": "accid-s7-minor-melodic-desc",
    "keySignatureId": "7s",
    "scaleType": "melodic-minor",
    "notation": "accidentals",
    "direction": "descending",
    "src": "./assets/notation/scales/accid-s7-minor-melodic-desc.svg"
  },
  {
    "assetId": "accid-s7-minor-natural",
    "keySignatureId": "7s",
    "scaleType": "natural-minor",
    "notation": "accidentals",
    "direction": "ascending",
    "src": "./assets/notation/scales/accid-s7-minor-natural.svg"
  },
  {
    "assetId": "keysig-0-major",
    "keySignatureId": "0",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-0-major.svg"
  },
  {
    "assetId": "keysig-0-minor-harmonic",
    "keySignatureId": "0",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-0-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-0-minor-melodic-asc",
    "keySignatureId": "0",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-0-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-0-minor-melodic-desc",
    "keySignatureId": "0",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-0-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-0-minor-natural",
    "keySignatureId": "0",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-0-minor-natural.svg"
  },
  {
    "assetId": "keysig-f1-major",
    "keySignatureId": "1f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f1-major.svg"
  },
  {
    "assetId": "keysig-f1-minor-harmonic",
    "keySignatureId": "1f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f1-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f1-minor-melodic-asc",
    "keySignatureId": "1f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f1-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f1-minor-melodic-desc",
    "keySignatureId": "1f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f1-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f1-minor-natural",
    "keySignatureId": "1f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f1-minor-natural.svg"
  },
  {
    "assetId": "keysig-f2-major",
    "keySignatureId": "2f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f2-major.svg"
  },
  {
    "assetId": "keysig-f2-minor-harmonic",
    "keySignatureId": "2f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f2-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f2-minor-melodic-asc",
    "keySignatureId": "2f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f2-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f2-minor-melodic-desc",
    "keySignatureId": "2f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f2-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f2-minor-natural",
    "keySignatureId": "2f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f2-minor-natural.svg"
  },
  {
    "assetId": "keysig-f3-major",
    "keySignatureId": "3f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f3-major.svg"
  },
  {
    "assetId": "keysig-f3-minor-harmonic",
    "keySignatureId": "3f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f3-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f3-minor-melodic-asc",
    "keySignatureId": "3f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f3-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f3-minor-melodic-desc",
    "keySignatureId": "3f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f3-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f3-minor-natural",
    "keySignatureId": "3f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f3-minor-natural.svg"
  },
  {
    "assetId": "keysig-f4-major",
    "keySignatureId": "4f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f4-major.svg"
  },
  {
    "assetId": "keysig-f4-minor-harmonic",
    "keySignatureId": "4f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f4-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f4-minor-melodic-asc",
    "keySignatureId": "4f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f4-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f4-minor-melodic-desc",
    "keySignatureId": "4f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f4-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f4-minor-natural",
    "keySignatureId": "4f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f4-minor-natural.svg"
  },
  {
    "assetId": "keysig-f5-major",
    "keySignatureId": "5f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f5-major.svg"
  },
  {
    "assetId": "keysig-f5-minor-harmonic",
    "keySignatureId": "5f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f5-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f5-minor-melodic-asc",
    "keySignatureId": "5f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f5-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f5-minor-melodic-desc",
    "keySignatureId": "5f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f5-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f5-minor-natural",
    "keySignatureId": "5f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f5-minor-natural.svg"
  },
  {
    "assetId": "keysig-f6-major",
    "keySignatureId": "6f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f6-major.svg"
  },
  {
    "assetId": "keysig-f6-minor-harmonic",
    "keySignatureId": "6f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f6-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f6-minor-melodic-asc",
    "keySignatureId": "6f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f6-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f6-minor-melodic-desc",
    "keySignatureId": "6f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f6-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f6-minor-natural",
    "keySignatureId": "6f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f6-minor-natural.svg"
  },
  {
    "assetId": "keysig-f7-major",
    "keySignatureId": "7f",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f7-major.svg"
  },
  {
    "assetId": "keysig-f7-minor-harmonic",
    "keySignatureId": "7f",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f7-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-f7-minor-melodic-asc",
    "keySignatureId": "7f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f7-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-f7-minor-melodic-desc",
    "keySignatureId": "7f",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-f7-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-f7-minor-natural",
    "keySignatureId": "7f",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-f7-minor-natural.svg"
  },
  {
    "assetId": "keysig-s1-major",
    "keySignatureId": "1s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s1-major.svg"
  },
  {
    "assetId": "keysig-s1-minor-harmonic",
    "keySignatureId": "1s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s1-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s1-minor-melodic-asc",
    "keySignatureId": "1s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s1-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s1-minor-melodic-desc",
    "keySignatureId": "1s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s1-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s1-minor-natural",
    "keySignatureId": "1s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s1-minor-natural.svg"
  },
  {
    "assetId": "keysig-s2-major",
    "keySignatureId": "2s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s2-major.svg"
  },
  {
    "assetId": "keysig-s2-minor-harmonic",
    "keySignatureId": "2s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s2-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s2-minor-melodic-asc",
    "keySignatureId": "2s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s2-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s2-minor-melodic-desc",
    "keySignatureId": "2s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s2-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s2-minor-natural",
    "keySignatureId": "2s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s2-minor-natural.svg"
  },
  {
    "assetId": "keysig-s3-major",
    "keySignatureId": "3s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s3-major.svg"
  },
  {
    "assetId": "keysig-s3-minor-harmonic",
    "keySignatureId": "3s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s3-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s3-minor-melodic-asc",
    "keySignatureId": "3s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s3-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s3-minor-melodic-desc",
    "keySignatureId": "3s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s3-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s3-minor-natural",
    "keySignatureId": "3s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s3-minor-natural.svg"
  },
  {
    "assetId": "keysig-s4-major",
    "keySignatureId": "4s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s4-major.svg"
  },
  {
    "assetId": "keysig-s4-minor-harmonic",
    "keySignatureId": "4s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s4-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s4-minor-melodic-asc",
    "keySignatureId": "4s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s4-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s4-minor-melodic-desc",
    "keySignatureId": "4s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s4-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s4-minor-natural",
    "keySignatureId": "4s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s4-minor-natural.svg"
  },
  {
    "assetId": "keysig-s5-major",
    "keySignatureId": "5s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s5-major.svg"
  },
  {
    "assetId": "keysig-s5-minor-harmonic",
    "keySignatureId": "5s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s5-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s5-minor-melodic-asc",
    "keySignatureId": "5s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s5-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s5-minor-melodic-desc",
    "keySignatureId": "5s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s5-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s5-minor-natural",
    "keySignatureId": "5s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s5-minor-natural.svg"
  },
  {
    "assetId": "keysig-s6-major",
    "keySignatureId": "6s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s6-major.svg"
  },
  {
    "assetId": "keysig-s6-minor-harmonic",
    "keySignatureId": "6s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s6-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s6-minor-melodic-asc",
    "keySignatureId": "6s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s6-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s6-minor-melodic-desc",
    "keySignatureId": "6s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s6-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s6-minor-natural",
    "keySignatureId": "6s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s6-minor-natural.svg"
  },
  {
    "assetId": "keysig-s7-major",
    "keySignatureId": "7s",
    "scaleType": "major",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s7-major.svg"
  },
  {
    "assetId": "keysig-s7-minor-harmonic",
    "keySignatureId": "7s",
    "scaleType": "harmonic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s7-minor-harmonic.svg"
  },
  {
    "assetId": "keysig-s7-minor-melodic-asc",
    "keySignatureId": "7s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s7-minor-melodic-asc.svg"
  },
  {
    "assetId": "keysig-s7-minor-melodic-desc",
    "keySignatureId": "7s",
    "scaleType": "melodic-minor",
    "notation": "key-signature",
    "direction": "descending",
    "src": "./assets/notation/scales/keysig-s7-minor-melodic-desc.svg"
  },
  {
    "assetId": "keysig-s7-minor-natural",
    "keySignatureId": "7s",
    "scaleType": "natural-minor",
    "notation": "key-signature",
    "direction": "ascending",
    "src": "./assets/notation/scales/keysig-s7-minor-natural.svg"
  }
];
